---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  name: pbindal-test-main-opc
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: "true"
  labels:
    appstudio.redhat.com/component: pbindal-test-main-opc
    appstudio.redhat.com/application: pbindal-test-main-opc
spec:
  image:
    name: pbindal-test-main/opc
    visibility: public
